package com.bdxh.classbrand.bean;

import java.io.Serializable;

public class DeviceVersionInfo implements Serializable {

    /**
     * id
     *
     * @mbg.generated 2021-04-07 10:39:28
     */
    private String id;

    /**
     * 版本ID
     *
     * @mbg.generated 2021-04-07 10:39:28
     */
    private String versionId;

    /**
     * 版本类型：1=普通类型
     *
     * @mbg.generated 2021-04-07 10:39:28
     */
    private String versionType;

    /**
     * 设备类型：1=电子班牌
     *
     * @mbg.generated 2021-04-07 10:39:28
     */
    private String deviceType;

    /**
     * 版本号
     *
     * @mbg.generated 2021-04-07 10:39:28
     */
    private String versionCode;

    /**
     * 包下载URL
     *
     * @mbg.generated 2021-04-07 10:39:28
     */
    private String packageUrl;

    /**
     * 版本描述
     *
     * @mbg.generated 2021-04-07 10:39:28
     */
    private String versionDesc;

    /**
     * 可用状态：1=可用，2=不可用
     *
     * @mbg.generated 2021-04-07 10:39:28
     */
    private String usableStatus;

    /**
     * 修改者管理员ID
     *
     * @mbg.generated 2021-04-07 10:39:28
     */
    private String reviserAdminId;

    /**
     * 创建者管理员ID
     *
     * @mbg.generated 2021-04-07 10:39:28
     */
    private String creatorAdminId;

    /**
     * 状态：1=活动，2=非活动
     *
     * @mbg.generated 2021-04-07 10:39:28
     */
    private String status;

    /**
     * 修改时间
     *
     * @mbg.generated 2021-04-07 10:39:28
     */
    private String modifyTime;

    /**
     * 创建时间
     *
     * @mbg.generated 2021-04-07 10:39:28
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table m_device_version_info
     *
     * @mbg.generated 2021-04-07 10:39:28
     */
    private static final long serialVersionUID = 1L;

    /**
     * id
     *
     * @mbg.generated 2021-04-07 10:39:28
     */
    public String getId() {
        return id;
    }

    /**
     * id
     *
     * @mbg.generated 2021-04-07 10:39:28
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * 版本ID
     *
     * @mbg.generated 2021-04-07 10:39:28
     */
    public String getVersionId() {
        return versionId;
    }

    /**
     * 版本ID
     *
     * @mbg.generated 2021-04-07 10:39:28
     */
    public void setVersionId(String versionId) {
        this.versionId = versionId;
    }

    /**
     * 版本类型：1=普通类型
     *
     * @mbg.generated 2021-04-07 10:39:28
     */
    public String getVersionType() {
        return versionType;
    }

    /**
     * 版本类型：1=普通类型
     *
     * @mbg.generated 2021-04-07 10:39:28
     */
    public void setVersionType(String versionType) {
        this.versionType = versionType;
    }

    /**
     * 设备类型：1=电子班牌
     *
     * @mbg.generated 2021-04-07 10:39:28
     */
    public String getDeviceType() {
        return deviceType;
    }

    /**
     * 设备类型：1=电子班牌
     *
     * @mbg.generated 2021-04-07 10:39:28
     */
    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType;
    }

    /**
     * 版本号
     *
     * @mbg.generated 2021-04-07 10:39:28
     */
    public String getVersionCode() {
        return versionCode;
    }

    /**
     * 版本号
     *
     * @mbg.generated 2021-04-07 10:39:28
     */
    public void setVersionCode(String versionCode) {
        this.versionCode = versionCode;
    }

    /**
     * 包下载URL
     *
     * @mbg.generated 2021-04-07 10:39:28
     */
    public String getPackageUrl() {
        return packageUrl;
    }

    /**
     * 包下载URL
     *
     * @mbg.generated 2021-04-07 10:39:28
     */
    public void setPackageUrl(String packageUrl) {
        this.packageUrl = packageUrl;
    }

    /**
     * 版本描述
     *
     * @mbg.generated 2021-04-07 10:39:28
     */
    public String getVersionDesc() {
        return versionDesc;
    }

    /**
     * 版本描述
     *
     * @mbg.generated 2021-04-07 10:39:28
     */
    public void setVersionDesc(String versionDesc) {
        this.versionDesc = versionDesc;
    }

    /**
     * 可用状态：1=可用，2=不可用
     *
     * @mbg.generated 2021-04-07 10:39:28
     */
    public String getUsableStatus() {
        return usableStatus;
    }

    /**
     * 可用状态：1=可用，2=不可用
     *
     * @mbg.generated 2021-04-07 10:39:28
     */
    public void setUsableStatus(String usableStatus) {
        this.usableStatus = usableStatus;
    }

    /**
     * 修改者管理员ID
     *
     * @mbg.generated 2021-04-07 10:39:28
     */
    public String getReviserAdminId() {
        return reviserAdminId;
    }

    /**
     * 修改者管理员ID
     *
     * @mbg.generated 2021-04-07 10:39:28
     */
    public void setReviserAdminId(String reviserAdminId) {
        this.reviserAdminId = reviserAdminId;
    }

    /**
     * 创建者管理员ID
     *
     * @mbg.generated 2021-04-07 10:39:28
     */
    public String getCreatorAdminId() {
        return creatorAdminId;
    }

    /**
     * 创建者管理员ID
     *
     * @mbg.generated 2021-04-07 10:39:28
     */
    public void setCreatorAdminId(String creatorAdminId) {
        this.creatorAdminId = creatorAdminId;
    }

    /**
     * 状态：1=活动，2=非活动
     *
     * @mbg.generated 2021-04-07 10:39:28
     */
    public String getStatus() {
        return status;
    }

    /**
     * 状态：1=活动，2=非活动
     *
     * @mbg.generated 2021-04-07 10:39:28
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * 修改时间
     *
     * @mbg.generated 2021-04-07 10:39:28
     */
    public String getModifyTime() {
        return modifyTime;
    }

    /**
     * 修改时间
     *
     * @mbg.generated 2021-04-07 10:39:28
     */
    public void setModifyTime(String modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * 创建时间
     *
     * @mbg.generated 2021-04-07 10:39:28
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * 创建时间
     *
     * @mbg.generated 2021-04-07 10:39:28
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    @Override
    public String toString() {
        return "DeviceVersionInfo{" +
                "id=" + id +
                ", versionId='" + versionId + '\'' +
                ", versionType=" + versionType +
                ", deviceType=" + deviceType +
                ", versionCode='" + versionCode + '\'' +
                ", packageUrl='" + packageUrl + '\'' +
                ", versionDesc='" + versionDesc + '\'' +
                ", usableStatus=" + usableStatus +
                ", reviserAdminId='" + reviserAdminId + '\'' +
                ", creatorAdminId='" + creatorAdminId + '\'' +
                ", status=" + status +
                ", modifyTime=" + modifyTime +
                ", createTime=" + createTime +
                '}';
    }
}
